# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

  
trigger:
- master

variables: 
  jobName: "Krishna's Folder/Testjob"
  serverEndpoint: 'Jenkins'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: JenkinsQueueJob@1
  displayName: 'Queue Jenkins Job: Testjob'
  inputs:
    serverEndpoint: '$(variables.serverEndpoint)'
    jobName: '$(variables.jobName)'
    parameterizedJob: true
    jobParameters: |
      BuildSourceBranch=$(Build.SourceBranch)
      BuildSourceBranchName=$(Build.SourceBranchName)
    captureConsole: true
    capturePipeline: true

- script: |
    echo "$BuildSourceBranch"
    echo "$BuildSourceBranchName"
    
  condition: succeededOrFailed()

